/*THONG KE CAC KHAI BAO MODULE
* CAC CHUONG TRINH MAU
* CAC DINH NGHIA
* ....
*/

#INCLUDE <16F887.H>
//KHAI BAO ADC
#device adc=10
#FUSES hs
// DAO DONG NOI 
#FUSES INTRC
// DAO DONG NOI _ SU DUNG CHAN RA6 RA7 LAM IO
#FUSES INTRC_IO
#USE DELAY(CLOCK=8MHZ)
//KHAI BAO UART
#USE rs232(baud=9600,xmit=pin_c6,rcv=pin_c7)
#use rs232(BAUD=9600,BITS=8,STOP=1,PARITY=N,RCV=PIN_C7,XMIT=PIN_C6)
//KHAI BAO LCD
#INCLUDE <LCD.C>
//KHAI BAO CO TRAN TIMER 
#bit TMR0IF =0x0b.2
#bit TMR1IF =0x0c.0
#bit TMR2IF =0x0c.1
//KHAI BAO MANG MA 7 DOAN 
const unsigned int8 code7seg[]={0xc0,0xf9,0xa4,0xb0,0x99,0x92,0x82,0xf8,0x80,0x90};

/* DINH NGHIA NUT NHAN, PULSE, LED*/

/* KHAI BAO BIEN */ 

/* CHUONG TRINH PHUC VU NGAT*/
#INT_RDA
VOID NGAT_NHAN()
{
   	
}

/* CHUONG TRINH CON */


/*-------------------SETUP--------------------------*/
LCD_INIT();

/* COUNTER */
SETUP_TIMER_1(T1_EXTERNAL|T1_DIV_BY_1);
SET_TIMER1(0);

/* ADC */
SETUP_ADC(ADC_CLOCK_INTERAL);   //INTERNAL
SETUP_ADC(ADC_CLOCK_DIV_32);   
//PORT 
SEETUP_ADC_PORTS(SAN5|VSS_VDD);

/* NGAT */
ENABLE_INTERRUPTS(GLOBAL);
ENABLE_INTERRUPTS(INT_RDA);

/* PWM */ 
SETUP_CCP1(CCP_PWM);   //RC2
SETUP_TIMER_2(T2_DIV_BY_16,249,1);

/*-------------------CAC CHUONG TRINH DAC BIET--------------------------*/

//CO SU THAY DOI 
	if(TEMP != old_TEMP)
	{
		putc(TEMP);
		old_TEMP=TEMP;
	}
//DELAY_MSX
	VOID DELAY_MSX(UNSIGNED INT16 TIME_MS)   //DELAY_MS(200);
	{
		FOR(INT16 I=0;I<TIME_MS;I++) //CHIA NHO DELAY RA THANH T LAN
		{
			DELAY_MS(1);  //MOI LAN DELAY 1 MS 
			IF(INPUT(STOP)==0) 
			{
				//CONG VIEC TUY THEO DE BAI YEU CAU
				//.......
				BREAK;  //TERMINATED 
			}
		}   
	}
//CHONG DOI NUT NHAN 
	IF(INPUT(ADJ)==0)
	{
		DELAY_MS(20);
		IF(INPUT(ADJ)==0)
		{
			//CONG VIEC - TUY THEO DE BAI
			//.........
			WHILE(INPUT(ADJ)==0);
		}
	}
/* DAO CHIEU DONG CO */ 
	//QUAY THUAN 
	//XUAT XUNG RC1, LOW RC2
	SET_PWM2_DUTY(100);   //(20/100*500)
	OUTPUT_LOW(PIN_C2);    
   	
	//QUAY NGHICH 
	//XUAT XUNG RC2, LOW RC1
	SET_PWM1_DUTY(350);   //(70/100*500)
	OUTPUT_LOW(PIN_C1); 

/* NUT RANDOM */
	FOR(INT16 I=0;I<10;I++)
	{
		//KTRA COI NUT RAND CO DDC NHAN KHOONG 
		// CO => XUAT CSAI GIA TRI TAI THOI DIEM DO 
		IF(INPUT(RAND)==0)
		{
			DELAY_MS(20);
			IF(INPUT(RAND)==0)
			{
				// CONG VIEC
				// XUAT LED 7 DOAN, ..... 
				LEVEL=I; //I LUC NAY CHINH LA SO NGAU NHIEN
				WHILE(INPUT(RAND)==0);
			}
		}
	} 
   	
/*-------------------CAC LENH DAC BIET--------------------------*/
// GOI DATA LEN LCD BANG PRINTF
PRINTF(LCD_PUTC,"DUTY=%3U",DUTY*10);

// GOI DATA LEN MAY TINH  BANG PRINTF
PRINTF("P=%3U,B=%05LU",SP,BOX);

//TAT XUNG 
T1_DIABLE
CCP_OFF


